[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install"

[deploy]
startCommand = "cd backend && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"
PORT = "5000"
MONGO_URI = "mongodb+srv://foojra:foojra123@cluster0.mongodb.net/foojra?retryWrites=true&w=majority"
JWT_SECRET = "foojra_super_secret_jwt_key_2024"
JWT_EXPIRE = "30d"